// AUTHENTICATION 
export const SET_AUTH = 'SET_AUTH';
export const SET_AUTH_FIELD = 'SET_AUTH_FIELD';

// USER
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// USER IMAGES
export const ADD_USER_IMAGES = 'ADD_USER_IMAGES';
export const DEL_USER_IMAGE = 'DEL_USER_IMAGE';
export const SET_USER_IMAGES = 'STATE_USER_IMAGE';

// ORDER 
export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_DELIVER = 'SET_DELIVER';
export const SET_TYPE = 'SET_TYPE';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const SET_ORDER = 'SET_ORDER';
export const SET_STATE = 'SET_STATE';

// ORDER - EXTRA
export const SET_ORDER_PAGE = 'SET_ORDER_PAGE';

// ORDER - DESCRIPTIONS - 
export const SET_ORDER_DESCRIPTION = 'SET_ORDER_DESCRIPTION';
export const ADD_ORDER_DESCRIPTION = 'ADD_ORDER_DESCRIPTION';
export const DEL_ORDER_DESCRIPTION = 'DEL_ORDER_DESCRIPTION';
export const UPDATE_FIELD_ORDER_DESCRIPTION = 'UPDATE_FIELD_ORDER_DESCRIPTION';

// ORDER - REQUESTS
export const SET_ORDER_REQUESTS = 'SET_ORDER_REQUESTS';
export const UPDATE_FIELD_APPLY_ORDER_REQUESTS = 'UPDATE_FIELD_APPLY_ORDER_REQUESTS';
export const SET_ORDER_REQUEST = 'SET_ORDER_REQUEST';
export const CLEAR_ORDER_REQUESTS = 'CLEAR_ORDER_REQUESTS';
export const SET_REQUESTS_FIELD = 'SET_REQUESTS_FIELD';

//ORDER FILES
export const ADD_ORDER_FILES = 'ADD_ORDER_FILES';
export const DEL_ORDER_FILE = 'DEL_ORDER_FILE';
export const SET_ORDER_FILES = 'SET_ORDER_FILES';
export const ADD_TMP_FILES = 'ADD_TMP_FILES';
export const DEL_TMP_FILES = 'DEL_TMP_FILES';
export const DEL_ALL_TMP_FILES = 'DEL_ALL_TMP_FILES';
export const CLEAR_ORDER_FILES = 'CLEAR_ORDER_FILES';

//ORDER TAGS
export const SET_ORDER_TAGS = 'SET_ORDER_TAGS';
export const ADD_ORDER_TAG = 'ADD_ORDER_TAG';
export const CLEAR_ORDER_TAGS = 'CLEAR_ORDER_TAG';
export const DEL_ORDER_TAG = 'DEL_ORDER_TAG';

// ORDERS 
export const SET_ORDERS = 'SET_ORDERS';
export const SET_AVAILABLE_ORDERS = 'SET_AVAILABLE_ORDERS';
export const SET_REQUESTED_ORDERS = 'SET_REQUESTED_ORDERS';

// API
export const CLEAR_API_RESPONSE = 'CLEAR_API_RESPONSE';
export const SET_API_RESPONSE = 'SET_API_RESPONSE';

// IMAGE PREVIEWER
export const CLOSE_PREVIEW_IMAGE = 'CLOSE_PREVIEW_IMAGE';
export const SHOW_PREVIEW_IMAGE = 'SHOW_PREVIEW_IMAGE';
export const SET_PREVIEW_URL = 'SET_PREVIEW_URL';
export const SET_PREVIEW_TITLE = 'SET_PREVIEW_TITLE';