// AUTHENTICATION 
export const SET_AUTH = 'SET_AUTH';
export const SET_AUTH_FIELD = 'SET_AUTH_FIELD';

// USER
export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

// USER IMAGES
export const ADD_USER_IMAGES = 'ADD_USER_IMAGES';
export const DEL_USER_IMAGE = 'DEL_USER_IMAGE';
export const SET_USER_IMAGES = 'STATE_USER_IMAGE';

// USER - ARCHIVED - DELIVERY
export const SET_ARCHIVED_DELIVERY_ORDERS = "SET_ARCHIVED_DELIVERY_ORDERS";
export const SET_SHOWN_ARCHIVED_FILES = "SET_SHOWN_ARCHIVED_FILES";

// ORDER 
export const SET_TITLE = 'SET_TITLE';
export const SET_DESCRIPTION = 'SET_DESCRIPTION';
export const SET_PAYMENT = 'SET_PAYMENT';
export const SET_DELIVER = 'SET_DELIVER';
export const SET_TYPE = 'SET_TYPE';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const SET_ORDER = 'SET_ORDER';
export const SET_STATE = 'SET_STATE';

// ORDER - EXTRA
export const SET_ORDER_PAGE = 'SET_ORDER_PAGE';

// ORDER - DESCRIPTIONS - 
export const SET_ORDER_DESCRIPTION = 'SET_ORDER_DESCRIPTION';
export const ADD_ORDER_DESCRIPTION = 'ADD_ORDER_DESCRIPTION';
export const DEL_ORDER_DESCRIPTION = 'DEL_ORDER_DESCRIPTION';
export const UPDATE_FIELD_ORDER_DESCRIPTION = 'UPDATE_FIELD_ORDER_DESCRIPTION';

// ORDER - REQUESTS
export const SET_ORDER_REQUESTS = 'SET_ORDER_REQUESTS';
export const UPDATE_FIELD_APPLY_ORDER_REQUESTS = 'UPDATE_FIELD_APPLY_ORDER_REQUESTS';
export const SET_ORDER_REQUEST = 'SET_ORDER_REQUEST';
export const CLEAR_ORDER_REQUESTS = 'CLEAR_ORDER_REQUESTS';
export const SET_REQUESTS_FIELD = 'SET_REQUESTS_FIELD';

// ORDER FILES
export const ADD_ORDER_FILES = 'ADD_ORDER_FILES';
export const DEL_ORDER_FILE = 'DEL_ORDER_FILE';
export const SET_ORDER_FILES = 'SET_ORDER_FILES';
export const ADD_TMP_FILES = 'ADD_TMP_FILES';
export const DEL_TMP_FILES = 'DEL_TMP_FILES';
export const DEL_ALL_TMP_FILES = 'DEL_ALL_TMP_FILES';
export const CLEAR_ORDER_FILES = 'CLEAR_ORDER_FILES';

// ORDER TAGS
export const SET_ORDER_TAGS = 'SET_ORDER_TAGS';
export const ADD_ORDER_TAG = 'ADD_ORDER_TAG';
export const CLEAR_ORDER_TAGS = 'CLEAR_ORDER_TAGS';
export const DEL_ORDER_TAG = 'DEL_ORDER_TAG';

// ORDER DELIVERY
export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const TOGGLE_OPEN_MODAL = 'TOGGLE_OPEN_MODAL';
export const SET_NEW_MODAL = 'SET_NEW_MODAL';
export const TOGGLE_NEW_MODAL = 'TOGGLE_NEW_MODAL';
export const SET_FINAL_MODAL = 'SET_FINAL_MODAL';
export const TOGGLE_FINAL_MODAL = 'TOGGLE_FINAL_MODAL';
export const SET_DELIVERYS = 'SET_DELIVERYS';
export const SET_DELIVERY = 'SET_DELIVERY';
export const UPDATE_FIELD_DELIVERY = 'UPDATE_FIELD_DELIVERY';
export const CLEAR_DELIVERY = 'CLEAR_DELIVERY';
export const ADD_DELIVERY_FILES = "ADD_DELIVERY_FILES";
export const DEL_DELIVERY_FILE = "DEL_DELIVERY_FILE";
export const ADD_TO_DELIVERYS = 'ADD_TO_DELIVERYS';
export const SET_DELIVERY_INVOICE = 'SET_DELIVERY_INVOICE';

//ORDER DELIVERY COMMENT
export const NEW_ORDER_DELIVERY_COMMENT = "NEW_ORDER_DELIVERY_COMMENT";
export const SET_ORDER_DELIVERY_COMMENT = "SET_ORDER_DELIVERY_COMMENT";

//ORDER MESSAGES

export const SET_ORDER_MESSAGES = "SET_ORDER_MESSAGES";
export const NEW_ORDER_MESSAGE = "NEW_ORDER_MESSAGE";

// ORDERS 
export const SET_ORDERS = 'SET_ORDERS';
export const SET_AVAILABLE_ORDERS = 'SET_AVAILABLE_ORDERS';
export const SET_REQUESTED_ORDERS = 'SET_REQUESTED_ORDERS';
export const SET_ARCHIVED_ORDERS = 'SET_ARCHIVED_ORDERS';
export const ADD_SEARCH_KEYS_AVAILABLE_ORDERS = 'ADD_SEARCH_KEYS_AVAILABLE_ORDERS';

// API
export const CLEAR_API_RESPONSE = 'CLEAR_API_RESPONSE';
export const SET_API_RESPONSE = 'SET_API_RESPONSE';

// IMAGE PREVIEWER
export const CLOSE_PREVIEW_IMAGE = 'CLOSE_PREVIEW_IMAGE';
export const SHOW_PREVIEW_IMAGE = 'SHOW_PREVIEW_IMAGE';
export const SET_PREVIEW_URL = 'SET_PREVIEW_URL';
export const SET_PREVIEW_TITLE = 'SET_PREVIEW_TITLE';

// GLOBAL MODAL
export const TOGGLE_GLOBAL_MODAL = 'TOGGLE_GLOBAL_MODAL';
export const RESET_GLOBAL_MODAL = 'RESET_GLOBAL_MODAL';
export const SET_ACTION = 'SET_ACTION';
export const CLEAR_ACTION = 'CLEAR_ACTION';
export const SET_PARAMETER = 'SET_PARAMETER';
export const SET_FIELDS = 'SET_FIELDS';

// NOTIFICATION
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_READ = 'SET_READ';
export const TOGGLE_NOTIFICATION_MODAL = 'TOGGLE_NOTIFICATION_MODAL'
export const OPEN_NOTIFICATION_MODAL = 'OPEN_NOTIFICATION_MODAL'
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

//LOADER
export const TOGGLE_LOADER_SYSTEM_BAR_ON = "TOGGLE_LOADER_SYSTEM_BAR_ON";
export const TOGGLE_LOADER_SYSTEM_BAR_OFF = "TOGGLE_LOADER_SYSTEM_BAR_OFF";