// AUTHENTICATION MODULE
export const SET_AUTH = 'SET_AUTH';
export const UPDATE_AUTH = 'UPDATE_AUTH';

// APICALL MODULE
export const CLEAR_API_RESPONSE = 'CLEAR_API_RESPONSE';
export const SET_API_RESPONSE = 'SET_API_RESPONSE';